version: '3.4'
services:
  timeoff:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production      
  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database_production
      - MYSQL_USER=tofuser
      - MYSQL_PASSWORD=tofpwd